import { PatientProfile } from './types';

export const PATIENT_PROFILES: PatientProfile[] = [
  {
    name: 'healthy-adult',
    baselineHr: 72,
    baselineSpo2: 98,
    baselineTemp: 36.6,
    baselineRr: 16,
    baselineSbp: 120,
    baselineDbp: 80,
    abnormalProbability: 0.05,
  },
  {
    name: 'elderly-stable',
    baselineHr: 68,
    baselineSpo2: 96,
    baselineTemp: 36.4,
    baselineRr: 18,
    baselineSbp: 135,
    baselineDbp: 85,
    abnormalProbability: 0.10,
  },
  {
    name: 'elderly-hypertensive',
    baselineHr: 78,
    baselineSpo2: 95,
    baselineTemp: 36.5,
    baselineRr: 19,
    baselineSbp: 155,
    baselineDbp: 95,
    abnormalProbability: 0.15,
  },
  {
    name: 'elderly-copd',
    baselineHr: 82,
    baselineSpo2: 92,
    baselineTemp: 36.7,
    baselineRr: 22,
    baselineSbp: 130,
    baselineDbp: 82,
    abnormalProbability: 0.20,
  },
  {
    name: 'post-surgical',
    baselineHr: 85,
    baselineSpo2: 94,
    baselineTemp: 37.2,
    baselineRr: 20,
    baselineSbp: 110,
    baselineDbp: 70,
    abnormalProbability: 0.15,
  },
];
